### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by jitsunen** [awslabs/aws-iot-device-sdk-java-v2#13]
Hello,

I am currently running into a roadblock because I want to use either the Java or the Nodejs SDK for a large IoT project. The released Java SDK doesn't have Jobs support. The official NodeJS SDK doesn't seem to be actively maintained.

What is the V2 Java SDK release ETA?

Thanks much

**Comment by graebm** [comment]
We hope to have the V2 SDKs for all languages (Java, [JS & NodeJS](https://github.com/awslabs/aws-iot-device-sdk-js-v2), [Python](https://github.com/awslabs/aws-iot-device-sdk-python-v2), [C++](https://github.com/awslabs/aws-iot-device-sdk-cpp-v2)) in a final state before the end of the year.

The V2 Java SDK should be usable right now if you're connecting directly over MQTT (Greengrass and websockets support are forthcoming).

The existing [Python SDK](https://github.com/aws/aws-iot-device-sdk-python) has Jobs support, if you don't like the idea of running on something still-in-development.

**Comment by jitsunen** [comment]
Thanks for your response, @graebm , I will take a look at the Python SDK for now.
